defaults:
  - dataset: pascal_voc
  - model: unet

checkpoints_path: "experiments/none_resnet34_2024-12-06_15-16-24"

hydra:
  sweeper:
    params:
      model: unet_resnet18
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: . # Set working dir to current directory
